# Generated by Django 5.0.4 on 2024-05-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperstarcomments',
            old_name='stars',
            new_name='star',
        ),
    ]
