# Generated by Django 5.0.4 on 2024-05-30 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_stars_paperstarcomments_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperwithtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='paperwithtag',
            name='paper',
        ),
        migrations.AddField(
            model_name='paperstarcomments',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papertextcomments',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaperSetWithTag',
        ),
        migrations.DeleteModel(
            name='PaperTags',
        ),
        migrations.DeleteModel(
            name='PaperWithTag',
        ),
    ]
