# Generated by Django 5.0.4 on 2024-05-30 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_paperwithtag_tag_remove_paperwithtag_paper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paperstarcomments',
            constraint=models.UniqueConstraint(fields=('paper', 'user'), name='unique_paper_user'),
        ),
    ]
