# Generated by Django 5.0.4 on 2024-05-30 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paperstarcomments_unique_paper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperstarcomments',
            name='star',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='stars must be at least 1'), django.core.validators.MaxValueValidator(10, message='stars cannot be more than 10')]),
        ),
    ]
