# Generated by Django 5.0.4 on 2024-05-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_paperstarcomments_star'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='papercited',
            constraint=models.UniqueConstraint(fields=('paper', 'cite_paper'), name='unique_paper_cites'),
        ),
        migrations.AddConstraint(
            model_name='papersetcontent',
            constraint=models.UniqueConstraint(fields=('paper', 'paper_set'), name='unique_paper_in_sets'),
        ),
    ]
