# Generated by Django 5.0.4 on 2024-06-02 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_papercited_unique_paper_cites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperset',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paperset',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='papersetcontent',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_paperset', to='api.paper'),
        ),
        migrations.AlterField(
            model_name='papersetcontent',
            name='paper_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_paper', to='api.paperset'),
        ),
    ]
